/*
 * dht11voter.h
 *
 *  Created on: 21 feb. 2019
 *      Author: user
 */

#ifndef SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DHT11VOTER_H_
#define SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DHT11VOTER_H_


float dht11md(float entries[3]);


#endif /* SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DHT11VOTER_H_ */
