/*
 * dht11_01.h
 *
 *  Created on: 4 mar. 2019
 *      Author: user
 */

#ifndef SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DHT11_01_H_
#define SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DHT11_01_H_


void ValuesPrinter (float h, float t);


#endif /* SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DHT11_01_H_ */
