/*
 * dynvoter.h
 *
 *  Created on: 3 mar. 2019
 *      Author: user
 */

#ifndef SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DYNVOTER_H_
#define SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DYNVOTER_H_


float vote(float sums, int total);


#endif /* SAPI_EXAMPLES_EDU_CIAA_NXP_BARE_METAL_TEMPERATURE_HUMIDITY_SENSORS_DHT11_01_SRC_DYNVOTER_H_ */
